### ISSUE TITLE
Кредитный счет создается с отрицательным начальным балансом

### ISSUE THREAD

**Issue by KolyanGrom** [KolyanGrom/javaqa_team_diplom_2#10]
**Описание**
Объект кредитного счёта с отрицательным начальным балансом не должен создаваться.

**Локация дефекта**
https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/a11b461a88075ec0b2c2813d7ffff03ef18ffd1b/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20

**Шаги воспроизведения**

1. Открыть [код программы](https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA.
2. Перейти в тест [`accountTest_1`](https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/a8876e9c479bfdfd1b2161ec56cc524e659d6727/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L144).
3. Вызвать метод  `Assertions.assertThrows` проверки выброса исключения вида `IllegalArgumentException`.
4. В поле выброса исключения задать: `IllegalArgumentException.class`.
5. В поле кода, который должен выбросить это исключение создать объект: `new CreditAccount`.
6. Выставить значение переменной `initialBalance` в -15.
7. Выставить значение переменной `creditLimit` в 15.
8. Выставить значение переменной `rate` в 10.
9. Запустить программу.
10. Посмотреть на вывод консоли.

_Ожидаемый результат:_ Выкидывается исключение: "Начальный баланс не может быть меньше нуля, а у вас: " + initialBalance. 

_Фактический результат:_ Тест `accountTest_1` провален. Исключения не выкидываются.

**Тест**
https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/a11b461a88075ec0b2c2813d7ffff03ef18ffd1b/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L67

**Скриншот**
![test_7](https://github.com/KolyanGrom/javaqa_team_diplom_2/assets/154681009/a6ff49a1-72df-4317-a855-f9b22868e854)

**Окружение**

- Операционная система: Windows 10 Pro

- DE: IntelliJ IDEA Community Edition 2023.3.3

- Java: OpenJDK11

**Comment by EvaGribova** [comment]
баг исправлен
