### ISSUE TITLE
Не выкидывается исключение, если изначальный баланс меньше мин баланса или больше макс баланса.

### ISSUE THREAD

**Issue by EvaGribova** [KolyanGrom/javaqa_team_diplom_2#11]
# Описание
Когда изначальный баланс меньше, чем мин баланс, или больше, чем макс баланс, должно появляться исключение, что баланс некорректный. 

# Локация дефекта
https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/6e341eaead56dee2be08e92aa044bdf893aef5a3/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1. Создать класс SavingAccountTest, создать тест shouldShowExceptionInitialBalance.
2. Вызвать метод Assertions.assertThrows  проверки выброса исключения вида IllegalArgumentException.
3. В поле выброса исключения указать его вид: IllegalArgumentException.class, в поле кода, который должен выбросить это исключение создать объект: new SavingAccount(500, 1_000, 10_000, 5), начальный баланс меньше минимального баланса.
4. Вызвать метод Assertions.assertThrows  проверки выброса исключения вида IllegalArgumentException.
5. В поле выброса исключения указать его вид: IllegalArgumentException.class, в поле кода, который должен выбросить это исключение создать объект: new SavingAccount(11_000, 1_000, 10_000, 5), начальный баланс больше максимального.
6. Запустить тест, посмотреть вывод на консоль.

*Ожидаемый результат:* Выкидывается исключение: 1. "Баланс не может быть меньше " + minBalance. 2. "Баланс не может быть больше " + maxBalance.

*Фактический результат:* Тест в SavingAccountTest провален. Исключения не выкидываются.

# Тест
https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/6e341eaead56dee2be08e92aa044bdf893aef5a3/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L109

# Скриншот
![screenshot-nimbusweb me-2024 03 19-15_30_37](https://github.com/KolyanGrom/javaqa_team_diplom_2/assets/155627172/4016711f-fd23-4465-8c25-1ba3179423bb)

# Окружение
* **Операционная система:** Windows 7 Максимальная
* **IDE:** IntelliJ IDEA Community Edition 2023.1.5
* **Java:** OpenJDK11

**Comment by KolyanGrom** [comment]
Баг исправлен @KolyanGrom
