### ISSUE TITLE
Когда мин баланс меньше 0 должно выкидываться исключение IllegalArgumentException.

### ISSUE THREAD

**Issue by EvaGribova** [KolyanGrom/javaqa_team_diplom_2#12]
# Описание
Если мин баланс отрицательный, должно появиться исключение о том, что мин баланс некорректен.

# Локация дефекта
https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/6e341eaead56dee2be08e92aa044bdf893aef5a3/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1. Создать класс SavingAccountTest, создать тест shouldShowExceptionMinBalance.
2. Вызвать метод Assertions.assertThrows  проверки выброса исключения вида IllegalArgumentException .
3. В поле выброса исключения указать его вид: IllegalArgumentException.class, в поле кода, который должен выбросить это исключение создать объект: new SavingAccount(2_000, -1_000, 10_000, 5) с отрицательным минимальным балансом.
4. Запустить тест, посмотреть вывод на консоль.

*Ожидаемый результат:* Тест пройден, будет выкидываться исключение: "Мин баланс не может быть отрицательным".

*Фактический результат:* Тест в SavingAccountTest провален. Исключение не будет выкидываться.

# Тест
https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/6e341eaead56dee2be08e92aa044bdf893aef5a3/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L116

# Скриншот
![screenshot-nimbusweb me-2024 03 19-15_33_40](https://github.com/KolyanGrom/javaqa_team_diplom_2/assets/155627172/90cf1c05-d186-42d5-b5d8-60f775441d02)

# Окружение
* **Операционная система:** Windows 7 Максимальная
* **IDE:** IntelliJ IDEA Community Edition 2023.1.5
* **Java:** OpenJDK11

**Comment by KolyanGrom** [comment]
Баг исправлен @KolyanGrom
