### ISSUE TITLE
При пополнении счета до максимального баланса включительно операция пополнения не проходит.

### ISSUE THREAD

**Issue by EvaGribova** [KolyanGrom/javaqa_team_diplom_2#2]
# Описание
Когда изначальный баланс пополняется до максимального баланса включительно, операция не проходит.

# Локация дефекта
https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/def1aafa6a2d57cc5534817091c5923a5d91e30d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L72

# Шаги воспроизведения

1. Создать класс SavingAccountTest.
2. Создать объект account класса SavingAccount с начальным балансом 2 000, мин балансом 1 000, макс балансом 10 000, ставкой 5.
3. Пополнить счет на 8 000 методом account.add.
4. Запустить тест, посмотреть вывод на консоли.

*Ожидаемый результат:* Итоговый счет равен 10 000, тест в SavingAccountTest пройден.

*Фактический результат:* Тест в SavingAccountTest провален. Итоговый счет равен изначальному балансу 2_000.

# Тест
https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/def1aafa6a2d57cc5534817091c5923a5d91e30d/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L23

# Скриншот
![screenshot-nimbusweb me-2024 03 19-11_35_28](https://github.com/KolyanGrom/javaqa_team_diplom_2/assets/155627172/9083b229-c939-4516-a56c-5a4a36d9e571)

# Окружение
* **Операционная система:** Windows 7 Максимальная
* **IDE:** IntelliJ IDEA Community Edition 2023.1.5
* **Java:** OpenJDK11

**Comment by KolyanGrom** [comment]
Баг исправлен @KolyanGrom
