### ISSUE TITLE
Итоговый баланс после покупки становится меньше, чем допустимый мин баланс.

### ISSUE THREAD

**Issue by EvaGribova** [KolyanGrom/javaqa_team_diplom_2#3]
# Описание
При совершении покупки с накопительного счета итоговый баланс может быть меньше допустимого минимального баланса.

# Локация дефекта
https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/def1aafa6a2d57cc5534817091c5923a5d91e30d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения

1. Создать класс SavingAccountTest.
2. Создать объект account класса SavingAccount с начальным балансом 2 000, мин балансом 1 500, макс балансом 10 000, ставкой 5.
3. Совершить покупку на 1 000 методом account.pay.
4. Запустить тест, посмотреть вывод на консоли.

*Ожидаемый результат:* Итоговый счет равен начальному балансу (2 000), тест в SavingAccountTest пройден, покупка не прошла.

*Фактический результат:* Тест в SavingAccountTest провален. Итоговый счет равен 1 000, покупка прошла.

# Тест
https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/def1aafa6a2d57cc5534817091c5923a5d91e30d/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L81

# Скриншот
![screenshot-nimbusweb me-2024 03 19-11_58_36](https://github.com/KolyanGrom/javaqa_team_diplom_2/assets/155627172/c9b291b3-500c-4547-8000-0af77a3dc8a7)

# Окружение
* **Операционная система:** Windows 7 Максимальная
* **IDE:** IntelliJ IDEA Community Edition 2023.1.5
* **Java:** OpenJDK11

**Comment by KolyanGrom** [comment]
Баг исправлен @KolyanGrom
