### ISSUE TITLE
Итоговый баланс равен первоначальному балансу, если совершить покупку до суммы мин баланса включительно.

### ISSUE THREAD

**Issue by EvaGribova** [KolyanGrom/javaqa_team_diplom_2#4]
# Описание
Когда совершается покупка и итоговый баланс должен быть равен мин балансу, то оплата не проходит и итоговый баланс остается равен изначальному.

# Локация дефекта
https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/def1aafa6a2d57cc5534817091c5923a5d91e30d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения

1. Создать класс SavingAccountTest.
2. Создать объект account класса SavingAccount с начальным балансом 2 000, мин балансом 1 500, макс балансом 10 000, ставкой 5.
3. Совершить покупку на 500 методом account.pay.
4. Запустить тест, посмотреть вывод на консоли.

*Ожидаемый результат:* Итоговый счет равен 1 500, тест в SavingAccountTest пройден.

*Фактический результат:* Тест в SavingAccountTest провален. Итоговый баланс равен первоначальному балансу(2 000).

# Тест
https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/def1aafa6a2d57cc5534817091c5923a5d91e30d/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L69

# Скриншот
![screenshot-nimbusweb me-2024 03 19-13_07_45](https://github.com/KolyanGrom/javaqa_team_diplom_2/assets/155627172/02c5b2c6-29f3-4f0e-912f-7d4b4105a6d4)

# Окружение
* **Операционная система:** Windows 7 Максимальная
* **IDE:** IntelliJ IDEA Community Edition 2023.1.5
* **Java:** OpenJDK11

**Comment by KolyanGrom** [comment]
Баг исправлен @KolyanGrom
