### ISSUE TITLE
Кредитный счет может имеет отрицательный баланс сверх кредитного лимита

### ISSUE THREAD

**Issue by KolyanGrom** [KolyanGrom/javaqa_team_diplom_2#5]
**Описание**
При совершении покупки на сумму превышающую кредитный лимит, происходит списание суммы с баланса, без каких либо ограничений.

**Локация дефекта**
https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/3fc38e7a57b37adcc21d1d8cce4e7297fcf8cb92/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20

**Шаги воспроизведения**
1. Открыть [код программы](https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA.
2. Перейти в тест [`payAboveCreditLimitMin`](https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/1f9fb4dabb66d35c5574047f28ee8dc06a80fba9/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L48C17-L48C39).
3. Создать объект `account` класса `CreditAccount`.
4. Выставить значение переменной `initialBalance` в 0.
5. Выставить значение переменной `creditLimit` в 10_000.
6. Выставить значение переменной `rate` в 15.
7. Вызвать метод `account.pay`.
8. Выставить значение переменной `amount` в 20_000.
9. Вызвать метод `Assertions.assertEquals`.
10. Выставить значение `expected` в 0.
11. Выставить значение `actual` в виде кода `account.getBalance()`.
12. Запустить программу.
13. Посмотреть на вывод консоли.

_Ожидаемый результат:_  Баланс равен 0, тест  `payAboveCreditLimitMin` пройден.

_Фактический результат:_ Тест `payAboveCreditLimitMin` провален. Баланс равен -20_000.

**Тест**
https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/3fc38e7a57b37adcc21d1d8cce4e7297fcf8cb92/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L35

**Скриншот**
![test_3](https://github.com/KolyanGrom/javaqa_team_diplom_2/assets/154681009/0bc1b20c-6135-43ab-a1c1-8b47ab26123d)

**Окружение**

- Операционная система: Windows 10 Pro

- IDE: IntelliJ IDEA Community Edition 2023.3.3

- Java: OpenJDK11

**Comment by EvaGribova** [comment]
Баг пофиксили
