### ISSUE TITLE
При совершении покупки списание происходит без учета баланса счета

### ISSUE THREAD

**Issue by KolyanGrom** [KolyanGrom/javaqa_team_diplom_2#8]
**Описание**
При совершении покупки на определенную сумму баланс становится равен отрицательному значению суммы покупки, без учета средств, находящихся на балансе.

**Локация дефекта**
https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/a11b461a88075ec0b2c2813d7ffff03ef18ffd1b/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L42

**Шаги воспроизведения**

1. Открыть [код программы](https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA.
2. Создать тест `payAndBalanceTest`.
3. Создать объект `account` класса `CreditAccount`.
4. Выставить значение переменной `initialBalance` в 20_000.
5. Выставить значение переменной `creditLimit` в 100_000.
6. Выставить значение переменной `rate` в 15.
7. Вызвать метод `account.pay`.
8. Выставить значение переменной `amount` в 5_000.
9. Вызвать метод `Assertions.assertEquals`.
10. Выставить значение `expected` в 15_000.
11. Выставить значение `actual` в виде кода `account.getBalance()`.
12. Запустить программу.
13. Посмотреть на вывод консоли.

_Ожидаемый результат:_ Итоговый балансе равен 15_000, тест `payAndBalanceTest `пройден.

_Фактический результат:_ Тест  `payAndBalanceTest ` провален. Итоговый баланс равен -5_000.

**Тест**
https://github.com/KolyanGrom/javaqa_team_diplom_2/blob/a11b461a88075ec0b2c2813d7ffff03ef18ffd1b/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L46

**Скриншот**
![test_5](https://github.com/KolyanGrom/javaqa_team_diplom_2/assets/154681009/fd508415-462c-49dd-8ffb-cab997f721fe)

**Окружение**

- Операционная система: Windows 10 Pro

- IDE: IntelliJ IDEA Community Edition 2023.3.3

- Java: OpenJDK11

**Comment by EvaGribova** [comment]
баг исправлен
